### ISSUE TITLE
Criar arquivos de configuração em formato JSON

### ISSUE THREAD

**Issue by igordsm** [Insper/LogCompTester#5]
Criar arquivo de configuração JSON que substitua `git_paths.txt`. Este arquivo deverá conter os nomes de usuários do blackboard e link para o github de todos os alunos, qual linguagem será usada no semestre e quais arquivos de teste serão usados no corretor. 

Depende de #2 .

@raulikeda

**Comment by lucassa3** [comment]
Também farei esse!

**Comment by raulikeda** [comment]
Resolvido no #7
